import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/common/fonts";
import Header from "@/components/Header";
import NestedTab from "@/components/NestedTab";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex flex-col items-center bg-tt-white text-tt-black">
                    {children}
                </main>
            </body>
        </html>
    );
}
