import type { Metadata } from "next";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>
        <Header/>
        <div className="flex gap-8 flex-col py-8 w-[1920px] min-h-[calc(100svh-57px)]">{children}</div>
    </>;
}
